fix: filter for correct usage/usagePage when finding xkeys devices
SuperFlyTV/xkeys pull request #93
Opened 2023-10-25 07:39 UTC by Julusian

fixes #92

The filtering might be overly strict, and needs to be verified on windows and macos to ensure the required properties are defined.

Tested with a XK24 and XK12-Jog

2023-10-25 07:47 UTC, nytamin commented
Hey @michaelhatPIengineering !
This PR basically adds the filter below (for browser WebHID only):

```typescript
function isValidXkeysUsage(device: HIDDevice): boolean {
	return !!device.collections.find(
		(collection) => collection.type === 1 && collection.usage === 1 && collection.usagePage === 12
	)
}
```

Does this filter look reasonable to you? Do you think we should go ahead and merge this fix right away or would you like to test it with various devices first? (I could prepare a test script for you)

2023-10-25 11:48 UTC, michaelhatPIengineering commented
Johan,

To 100% and to future proof this, we should add   && collection.writelength > 20

or what ever the way to see the write length of the "device"

There are some Multi-media devices that also use page 12 so we always check both.

Also, this problem is not just a browser problem, all other OSs could change how they enumerate and would not be out of spec.

So, this filter should be added to all.

MHH

________________________________
From: Johan Nyman ***@***.***>
Sent: Wednesday, October 25, 2023 3:47 AM
To: SuperFlyTV/xkeys ***@***.***>
Cc: Michael Hetherington ***@***.***>; Mention ***@***.***>
Subject: Re: [SuperFlyTV/xkeys] fix: filter for correct usage/usagePage when finding xkeys devices (PR #93)


Hey @michaelhatPIengineering<https://github.com/michaelhatPIengineering> !
This PR basically adds the filter below (for browser WebHID only):

function isValidXkeysUsage(device: HIDDevice): boolean {
        return !!device.collections.find(
                (collection) => collection.type === 1 && collection.usage === 1 && collection.usagePage === 12
        )
}

Does this filter look reasonable to you? Do you think we should go ahead and merge this fix right away or would you like to test it with various devices first? (I could prepare a test script for you)

—
Reply to this email directly, view it on GitHub<https://github.com/SuperFlyTV/xkeys/pull/93#issuecomment-1778702445>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AS6L3QW5VG2XKKQXGPJQXPTYBC725AVCNFSM6AAAAAA6O4W4OGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONZYG4YDENBUGU>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-10-25 12:30 UTC, michaelhatPIengineering commented
We are checking on how this works with all our device descriptors.

A test script might be good.


________________________________
From: Johan Nyman ***@***.***>
Sent: Wednesday, October 25, 2023 3:47 AM
To: SuperFlyTV/xkeys ***@***.***>
Cc: Michael Hetherington ***@***.***>; Mention ***@***.***>
Subject: Re: [SuperFlyTV/xkeys] fix: filter for correct usage/usagePage when finding xkeys devices (PR #93)


Hey @michaelhatPIengineering<https://github.com/michaelhatPIengineering> !
This PR basically adds the filter below (for browser WebHID only):

function isValidXkeysUsage(device: HIDDevice): boolean {
        return !!device.collections.find(
                (collection) => collection.type === 1 && collection.usage === 1 && collection.usagePage === 12
        )
}

Does this filter look reasonable to you? Do you think we should go ahead and merge this fix right away or would you like to test it with various devices first? (I could prepare a test script for you)

—
Reply to this email directly, view it on GitHub<https://github.com/SuperFlyTV/xkeys/pull/93#issuecomment-1778702445>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AS6L3QW5VG2XKKQXGPJQXPTYBC725AVCNFSM6AAAAAA6O4W4OGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONZYG4YDENBUGU>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-10-25 13:55 UTC, KhangxLi commented
it seems like the fix worked on Mac, but not on Windows

2023-10-25 14:32 UTC, KhangxLi commented
looks like `collection.type === 0` for XKeys XK-80 on Windows

2023-10-25 14:57 UTC, michaelhatPIengineering commented
I reviewed with our firmware engineer; she recommends:

filter on:

VID
PID
Usage page 12
write length > 20

to get the "device" supported by this lib.

other things are redundant or not consistent over all OSs

________________________________
From: Khang Li ***@***.***>
Sent: Wednesday, October 25, 2023 10:32 AM
To: SuperFlyTV/xkeys ***@***.***>
Cc: Michael Hetherington ***@***.***>; Mention ***@***.***>
Subject: Re: [SuperFlyTV/xkeys] fix: filter for correct usage/usagePage when finding xkeys devices (PR #93)


looks like collection.type === 0 for XKeys XK-80 on Windows

—
Reply to this email directly, view it on GitHub<https://github.com/SuperFlyTV/xkeys/pull/93#issuecomment-1779417874>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AS6L3QVOF6GVOBTF7TXARXTYBEPINAVCNFSM6AAAAAA6O4W4OGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONZZGQYTOOBXGQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-11-01 15:41 UTC, Julusian commented
OK, I have stripped out some of the conditions, and left it checking `usagePage` and vendorId.
It is validating the productId later, so I don't think it is necessary to do at this early stage, especially as the user prompt isnt doing a filter on productId.

I haven't added a writeLength check, as doing so requires digging deeply into multiple layers of arrays and objects and that makes me a little uneasy about the reliability of doing so. Although each of linux, macos and windows did produce what appeared to be the same data for it:

![image](https://github.com/SuperFlyTV/xkeys/assets/1327476/c1966e68-8300-45d2-96fc-55d6d6bc80c5)

2023-11-01 15:47 UTC, michaelhatPIengineering commented
We have found that writeLenght is important to avoid confusion with multi-media which is also the same usage page.

________________________________
From: Julian Waller ***@***.***>
Sent: Wednesday, November 1, 2023 11:41 AM
To: SuperFlyTV/xkeys ***@***.***>
Cc: Michael Hetherington ***@***.***>; Mention ***@***.***>
Subject: Re: [SuperFlyTV/xkeys] fix: filter for correct usage/usagePage when finding xkeys devices (PR #93)


I have stripped out some of the conditions, and left it checking usagePage and vendorId.
It is validating the productId later, so I don't think it is necessary to do at this early stage, especially as the user prompt isnt doing a filter on productId.

I haven't added a writeLength check, as doing so requires digging deeply into multiple layers of arrays and objects and that makes me a little uneasy about the reliability of doing so. Although each of linux, macos and windows did produce what appeared to be the same data for it:

[image]<https://user-images.githubusercontent.com/1327476/279719982-c1966e68-8300-45d2-96fc-55d6d6bc80c5.png>

—
Reply to this email directly, view it on GitHub<https://github.com/SuperFlyTV/xkeys/pull/93#issuecomment-1789184419>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AS6L3QXNLNXCMQOKLYMOWF3YCJUTTAVCNFSM6AAAAAA6O4W4OGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOBZGE4DINBRHE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-11-01 16:40 UTC, Julusian commented
ok, I have added that check. The function now looks like:
```typescript
function isValidXkeysUsage(device: HIDDevice): boolean {
	if (device.vendorId !== XKEYS_VENDOR_ID) return false

	return !!device.collections.find((collection) => {
		if (collection.usagePage !== 12) return false

		// Check the write-length of the device is > 20
		return !!collection.outputReports?.find((report) => !!report.items?.find((item) => item.reportCount ?? 0 > 20))
	})
}
```
I have tested that this new version still works on windows, macos and linux

2023-11-01 17:18 UTC, michaelhatPIengineering commented
Looks good, we have found that those checks always work in all our other projects as well.

Thanks

________________________________
From: Julian Waller ***@***.***>
Sent: Wednesday, November 1, 2023 12:40 PM
To: SuperFlyTV/xkeys ***@***.***>
Cc: Michael Hetherington ***@***.***>; Mention ***@***.***>
Subject: Re: [SuperFlyTV/xkeys] fix: filter for correct usage/usagePage when finding xkeys devices (PR #93)


ok, I have added that check. The function now looks like:

function isValidXkeysUsage(device: HIDDevice): boolean {
        if (device.vendorId !== XKEYS_VENDOR_ID) return false

        return !!device.collections.find((collection) => {
                if (collection.usagePage !== 12) return false

                // Check the write-length of the device is > 20
                return !!collection.outputReports?.find((report) => !!report.items?.find((item) => item.reportCount ?? 0 > 20))
        })
}

I have tested that this new version still works on windows, macos and linux

—
Reply to this email directly, view it on GitHub<https://github.com/SuperFlyTV/xkeys/pull/93#issuecomment-1789288728>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AS6L3QQENVRQXM7GUFHYAO3YCJ3Q3AVCNFSM6AAAAAA6O4W4OGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOBZGI4DQNZSHA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-11-02 08:15 UTC, nytamin requested changes

2023-11-02 08:15 UTC, nytamin commented on packages/webhid/src/methods.ts
> +		throw new Error('Failed to initialise device')
We should throw the original error here

2023-11-02 08:27 UTC, merged